// ============================================================
// SECTION DDL (DROP & CREATE TABLES)
// ============================================================
const TABLES_QUERIES = [
    // --- NETTOYAGE (Ordre inverse pour éviter les erreurs de clés étrangères) ---
    { name: "Drop PERTE", sql: `BEGIN EXECUTE IMMEDIATE 'DROP TABLE PERTE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;` },
    { name: "Drop VENTE", sql: `BEGIN EXECUTE IMMEDIATE 'DROP TABLE VENTE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;` },
    { name: "Drop RECOLTE", sql: `BEGIN EXECUTE IMMEDIATE 'DROP TABLE RECOLTE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;` },
    { name: "Drop VARIETE", sql: `BEGIN EXECUTE IMMEDIATE 'DROP TABLE VARIETE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;` },
    { name: "Drop PRODUIT", sql: `BEGIN EXECUTE IMMEDIATE 'DROP TABLE PRODUIT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;` },

    // --- CRÉATION DES TABLES ---

    // 1. PRODUIT
    {
        name: "Create PRODUIT",
        sql: `CREATE TABLE PRODUIT (
                id_produit NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nom_produit VARCHAR2(50) NOT NULL UNIQUE
              )`
    },

    // 2. VARIETE (Avec colonne stock_actuel_kg)
    {
        name: "Create VARIETE",
        sql: `CREATE TABLE VARIETE (
                id_variete NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nom_variete VARCHAR2(100) NOT NULL,
                description VARCHAR2(255),
                stock_actuel_kg NUMBER(12,2) DEFAULT 0,
                id_produit NUMBER NOT NULL,
                FOREIGN KEY (id_produit) REFERENCES PRODUIT(id_produit),
                CHECK (stock_actuel_kg >= 0)
              )`
    },

    // 3. RECOLTE
    {
        name: "Create RECOLTE",
        sql: `CREATE TABLE RECOLTE (
                id_recolte NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                date_rec TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                qte_kg NUMBER(10,2) NOT NULL CHECK (qte_kg > 0),
                id_variete NUMBER NOT NULL,
                FOREIGN KEY (id_variete) REFERENCES VARIETE(id_variete)
              )`
    },

    // 4. VENTE
    {
        name: "Create VENTE",
        sql: `CREATE TABLE VENTE (
                id_vente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                date_vente TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                qte_kg NUMBER(10,2) NOT NULL CHECK (qte_kg > 0),
                prix_unitaire NUMBER(10,2) NOT NULL CHECK (prix_unitaire >= 0),
                id_variete NUMBER NOT NULL,
                FOREIGN KEY (id_variete) REFERENCES VARIETE(id_variete)
              )`
    },

    // 5. PERTE
    {
        name: "Create PERTE",
        sql: `CREATE TABLE PERTE (
                id_perte NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                date_perte TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                qte_kg NUMBER(10,2) NOT NULL CHECK (qte_kg > 0),
                id_variete NUMBER NOT NULL,
                motif VARCHAR2(100),
                FOREIGN KEY (id_variete) REFERENCES VARIETE(id_variete)
              )`
    }
];

module.exports = TABLES_QUERIES;
